//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ANFramework_UIManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ANFramework.UIManager), typeof(ANFramework.BaseBehaviour));
		L.RegFunction("Init", Init);
		L.RegFunction("SetUIFolderPath", SetUIFolderPath);
		L.RegFunction("OpenUI", OpenUI);
		L.RegFunction("CleseUI", CleseUI);
		L.RegFunction("DestroyUI", DestroyUI);
		L.RegFunction("New", _CreateANFramework_UIManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateANFramework_UIManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ANFramework.UIManager obj = new ANFramework.UIManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ANFramework.UIManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ANFramework.UIManager obj = (ANFramework.UIManager)ToLua.CheckObject<ANFramework.UIManager>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUIFolderPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ANFramework.UIManager obj = (ANFramework.UIManager)ToLua.CheckObject<ANFramework.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetUIFolderPath(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ANFramework.UIManager obj = (ANFramework.UIManager)ToLua.CheckObject<ANFramework.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OpenUI(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CleseUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ANFramework.UIManager obj = (ANFramework.UIManager)ToLua.CheckObject<ANFramework.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CleseUI(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ANFramework.UIManager obj = (ANFramework.UIManager)ToLua.CheckObject<ANFramework.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DestroyUI(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

